# Generated by Django 2.1.4 on 2020-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrainformation',
            name='amount_withdrawable',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextrainformation',
            name='gold',
            field=models.BooleanField(default=False),
        ),
    ]
