# Generated by Django 3.2.7 on 2023-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0002_auto_20200629_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='Transaction_Amount',
            field=models.CharField(default='5000', max_length=500),
        ),
    ]
