# Generated by Django 3.2.7 on 2023-10-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0003_usermessages_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='wallet_address',
            field=models.CharField(default='0x1ddsdfewrtbfhtrregwhty76846uyjesfgwe4tfeq34f34rqf', max_length=500),
        ),
    ]
